In [1]:
"""Main file for running annealed Langevin dynamics for new material sampling."""
from __future__ import annotations
from pathlib import Path
from types import SimpleNamespace

import torch

from chggen.pl_data.dataset import CHGNetDataset
from chggen.pl_modules.model_egnn import CHGGen
from chggen.common.data_utils import get_scaler

/home/xzdai/anaconda3/envs/chggen/lib/python3.8/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
dataset = CHGNetDataset(
    path='/home/xzdai/ceder_group/material_dircovery/chggen_old/data/perov_5/test_zpc.csv',
    name = 'A_good_name',
    prop_list = ['heat_all'],
)

100%|██████████| 50/50 [00:00<00:00, 320.43it/s]


In [3]:
lattice_scaler = get_scaler(dataset= dataset)

model_hparams ={'latent_dim': 64, 'hidden_dim': 128, 
                'predict_property': True, 'property_dim': 1,  
                'load_pretrain': True, 
                'fc_num_layers': 1, 
                'sigma_F_begin': 10.0, 'sigma_F_end': 0.01, 
                'sigma_L_begin': 1.0, 'sigma_L_end': 0.01, 
                'type_sigma_begin': 5.0, 'type_sigma_end': 0.01,
                'max_atoms': 20, 
                'num_noise_level': 1, 
                'lattice_scale_method': 'scale_length', 
                'cost_natom': 1.0, 'cost_coord': 10.0, 'cost_type': 1.0, 'cost_lattice': 10.0, 'cost_composition': 1.0, 'cost_edge': 10.0, 'cost_property': 1.0,
                'beta': 0.01,
                'teacher_forcing_lattice': True,
                'teacher_forcing_max_epoch': 1000,
                'decoder': 'egnn'}

chggen = CHGGen(
    hparams_dict = model_hparams, lattice_scaler = lattice_scaler, 
)

device = torch.device('cpu')
checkpoint_path = "/home/xzdai/ceder_group/material_dircovery/chggen_old/test_models/perov/trainer_perov.ckpt"
chggen = chggen.load_from_checkpoint(checkpoint_path = checkpoint_path)
chggen.lattice_scaler = lattice_scaler
chggen.to(device = device)


/home/xzdai/ceder_group/material_dircovery/chggen_old/chggen/common/data_utils.py:655: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:245.)
  targets = torch.tensor([d[key] for d in data_list])
/home/xzdai/ceder_group/material_dircovery/chggen_old/chggen/common/data_utils.py:619: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float)


CHGNet initialized with 400,438 parameters
CHGNet initialized with 400,438 parameters
CHGNet initialized with 400,438 parameters
CHGNet initialized with 400,438 parameters


CHGGen(
  (mse_composition): MSELoss()
  (wnd): wND()
  (encoder3d): CHGNet_encoder(
    (composition_model): AtomRef(
      (fc): Linear(in_features=94, out_features=1, bias=False)
    )
    (graph_converter): CrystalGraphConverter(algorithm='legacy', atom_graph_cutoff=5, bond_graph_cutoff=3)
    (atom_embedding): AtomEmbedding(
      (embedding): Embedding(94, 64)
    )
    (bond_basis_expansion): BondEncoder(
      (rbf_expansion_ag): RadialBessel(
        (smooth_cutoff): CutoffPolynomial()
      )
      (rbf_expansion_bg): RadialBessel(
        (smooth_cutoff): CutoffPolynomial()
      )
    )
    (bond_embedding): Linear(in_features=9, out_features=64, bias=False)
    (bond_weights_ag): Linear(in_features=9, out_features=64, bias=False)
    (bond_weights_bg): Linear(in_features=9, out_features=64, bias=False)
    (angle_basis_expansion): AngleEncoder(
      (fourier_expansion): Fourier()
    )
    (angle_embedding): Linear(in_features=9, out_features=64, bias=False)
    (atom_con

In [4]:
def sample_composition(composition_prob, num_atoms):
    """Sample composition such that it exactly satisfies composition_prob.
    
    Args:
        composition_prob (Tensor): The composition probability. The shape should be
            (num of structures, MAX_ATOMIC_NUM).
        num_atoms (Tensor): The number of atoms for each structure. The shape should
            be (num of structures).
    
    Returns:
        all_sampled_comp (Tensor): The sampled composition. The shape should be
            (num of atoms).
    """
    all_sampled_comp = []

    for comp_prob, num_atom in zip(list(composition_prob), list(num_atoms)):
        comp_num = torch.round(comp_prob * num_atom)
        atom_type = torch.nonzero(comp_num, as_tuple=True)[0]
        atom_num = comp_num[atom_type].long()

        sampled_comp = atom_type.repeat_interleave(atom_num, dim=0)

        # if the rounded composition gives less atoms, sample the rest
        if sampled_comp.size(0) < num_atom:
            left_atom_num = num_atom - sampled_comp.size(0)

            left_comp_prob = comp_prob - comp_num.float() / num_atom

            left_comp_prob[left_comp_prob < 0.] = 0.
            left_comp = torch.multinomial(
                left_comp_prob, num_samples=left_atom_num, replacement=True)
            # convert to atomic number
            left_comp = left_comp + 1
            sampled_comp = torch.cat([sampled_comp, left_comp], dim=0)

        sampled_comp = sampled_comp[torch.randperm(sampled_comp.size(0))]
        sampled_comp = sampled_comp[:num_atom]
        all_sampled_comp.append(sampled_comp)

    all_sampled_comp = torch.cat(all_sampled_comp, dim=0)
    assert all_sampled_comp.size(0) == num_atoms.sum()
    return all_sampled_comp


In [5]:
z = torch.randn(1, 64, requires_grad= True, device = device)
(num_atoms, 
pred_lengths_and_angles, 
pred_lengths, 
pred_angles, 
composition) = chggen.decode_stats(z)
num_atoms, pred_lengths_and_angles, pred_lengths, pred_angles, composition[0]

/home/xzdai/ceder_group/material_dircovery/chggen_old/chggen/common/data_utils.py:630: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X = torch.tensor(X, dtype=torch.float)


(tensor([5]),
 tensor([[ 4.7001e-01,  4.6271e-01,  4.6854e-01, -3.3318e-05,  3.5767e-05,
           2.8731e-04]], grad_fn=<AddmmBackward0>),
 tensor([[4.3180, 4.3155, 4.3175]]),
 tensor([[90., 90., 90.]]),
 tensor([7.6753e-07, 1.4844e-06, 2.3530e-05, 7.9639e-05, 1.9143e-05, 1.3707e-06,
         9.0572e-02, 4.1339e-01, 8.4708e-02, 8.8982e-07, 3.0252e-03, 4.4701e-03,
         2.8215e-03, 4.3986e-04, 7.6346e-07, 5.3164e-02, 2.0582e-06, 6.3109e-07,
         1.2438e-03, 9.2950e-03, 1.4337e-02, 7.7219e-03, 6.4466e-03, 5.0543e-03,
         5.2389e-03, 3.4719e-03, 2.4543e-03, 8.4540e-04, 1.8333e-03, 3.4105e-03,
         7.1345e-03, 5.8397e-03, 7.9941e-03, 1.0937e-06, 9.6777e-07, 9.8261e-07,
         1.6031e-03, 1.1739e-02, 9.4499e-03, 1.4325e-02, 8.8305e-03, 9.4916e-03,
         9.2784e-07, 5.9655e-03, 3.3845e-03, 4.5505e-03, 4.8278e-03, 6.5731e-03,
         1.2983e-02, 1.9844e-02, 1.2584e-02, 1.0226e-02, 5.1838e-07, 1.1699e-06,
         3.1605e-03, 1.4790e-02, 1.1875e-02, 9.3587e-07, 8.6987e-

In [16]:
sample_composition(composition, num_atoms)

tensor([ 9, 22,  7,  9,  7])

In [42]:
from types import SimpleNamespace

ld_kwargs = SimpleNamespace(
    n_step_each = 10,
    step_lr = 1e-6,
    min_sigma = 0,
    save_traj = False,
    disable_bar = False,
    compute_force = True,
    beta_c = 0,         # property update rate
    beta_f = 0,         # atomic force update rate                          
)
ld_kwargs.n_step_each

10

In [43]:
results = chggen.langevin_dynamics_guidance(
    z = z, 
    prop_guidance = torch.tensor(-0.05, device= device), 
    ld_kwargs= ld_kwargs
)

  0%|          | 0/50 [00:00<?, ?it/s]

sigma step: 0
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.317963123321538 4.315497398376473 4.317465782165527
 angles : 90.000002504478 90.00000250447812 89.9999974955219
 volume : 80.45234224279402
      A : 4.317963123321533 0.0 -1.887441669623513e-07
      B : 1.886363776293365e-07 4.315497398376465 -1.886363776293365e-07
      C : 0.0 0.0 4.317465782165527
    pbc : True True True
PeriodicSite: O (0.03905, 2.733, 0.3496) [0.009043, 0.6334, 0.08098]
PeriodicSite: Sb (0.2364, 2.168, 3.849) [0.05474, 0.5024, 0.8916]
PeriodicSite: Pb (1.409, 0.3675, 4.261) [0.3262, 0.08516, 0.987]
PeriodicSite: Ca (2.088, 0.6716, 2.538) [0.4836, 0.1556, 0.5879]
PeriodicSite: O (2.013, 3.744, 2.998) [0.4662, 0.8676, 0.6943]]
step: 1
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.47571416169738 4.465282285724494 4.147268524121782
 angles : 90.72232195029089 92.17336549740402 91.97693069842542
 volume : 82.76756295062029
      A : 4.475130081176758 -0.017934484407305717 -0.07004547119140625
 

  2%|▏         | 1/50 [00:00<00:28,  1.72it/s]

step: 8
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.9744936950565215 4.728777632047602 3.9702784638176727
 angles : 90.22421268246356 93.45497831333265 91.44592210732804
 volume : 93.19313739570904
      A : 4.943975448608398 -0.06303519010543823 -0.5465536117553711
      B : -0.022766131907701492 4.716763496398926 0.336097776889801
      C : 0.19264641404151917 -0.2964288294315338 3.954507350921631
    pbc : True True True
PeriodicSite: O (1.091, 2.711, 2.847) [0.1965, 0.621, 0.6942]
PeriodicSite: Sb (4.995, 0.8959, 3.448) [0.9732, 0.2648, 0.9839]
PeriodicSite: Pb (0.4694, 3.158, 3.459) [0.06623, 0.7222, 0.8225]
PeriodicSite: Ca (3.46, 3.115, 1.376) [0.688, 0.6937, 0.3841]
PeriodicSite: O (2.71, 1.024, 1.234) [0.5351, 0.2472, 0.3649]]
step: 9
CaSbPbO2
[Structure Summary
Lattice
    abc : 5.206374587834782 4.685588004849512 3.905910227304211
 angles : 85.78432171477453 94.39048091986415 90.94201402806706
 volume : 94.74213159302597
      A : 5.178440093994141 0.07547417283058167 -0

  4%|▍         | 2/50 [00:01<00:24,  1.99it/s]

step: 8
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.904552404293874 4.901466628545442 3.7379498678287866
 angles : 95.1631338543876 95.19745088021808 86.74022856178124
 volume : 89.01833870835296
      A : 4.862829685211182 0.628132700920105 -0.11389051377773285
      B : -0.3519350290298462 4.888330936431885 -0.06882951408624649
      C : -0.2155965268611908 -0.30043697357177734 3.719613552093506
    pbc : True True True
PeriodicSite: O (3.141, 2.269, 3.351) [0.7182, 0.4291, 0.9309]
PeriodicSite: Sb (4.286, 4.254, 1.487) [0.9571, 0.7744, 0.4433]
PeriodicSite: Pb (2.7, 3.487, 2.694) [0.6379, 0.6779, 0.7563]
PeriodicSite: Ca (1.923, 2.341, 2.406) [0.4585, 0.4611, 0.6694]
PeriodicSite: O (3.93, 3.497, 2.476) [0.8862, 0.6449, 0.7047]]
step: 9
CaSbPbO2
[Structure Summary
Lattice
    abc : 5.082148680528245 4.97446539763325 3.7741063310818275
 angles : 91.02035568334682 92.0301806890269 90.68462010492125
 volume : 95.33051359268819
      A : 5.0553460121154785 0.501549243927002 0.141986

  6%|▌         | 3/50 [00:01<00:21,  2.22it/s]

step: 9
CaSbPbO2
[Structure Summary
Lattice
    abc : 5.0271446535352595 5.4120394059255394 3.868830023608864
 angles : 82.72511948704755 99.93500136387432 88.52802910784905
 volume : 102.72478869228898
      A : 4.958440780639648 0.7529603242874146 -0.34510743618011475
      B : -0.6671059727668762 5.369726181030273 0.10573974251747131
      C : -0.4653743803501129 0.3606567680835724 3.82376766204834
    pbc : True True True
PeriodicSite: O (3.91, 4.817, 0.7991) [0.915, 0.7506, 0.2708]
PeriodicSite: Sb (2.23, 1.965, 1.04) [0.5156, 0.2728, 0.311]
PeriodicSite: Pb (2.662, 2.62, 3.321) [0.6678, 0.3324, 0.9197]
PeriodicSite: Ca (4.295, 2.34, 2.318) [0.9648, 0.2545, 0.6862]
PeriodicSite: O (-0.2924, 1.08, 3.446) [0.04372, 0.1345, 0.9013]]
sigma step: 3
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 5.257113539544911 5.185952443396176 3.9328475629906174
 angles : 82.64284998670564 100.04373004239609 88.64177205885109
 volume : 104.59298060393179
      A : 5.202645778656006 0.72617810

  8%|▊         | 4/50 [00:01<00:20,  2.27it/s]

sigma step: 4
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 5.412427464567807 5.29722133133746 3.5860954689681175
 angles : 84.3244799934854 113.62137931053228 87.8434899263927
 volume : 93.40275328657071
      A : 5.318152904510498 0.8436204195022583 -0.547654390335083
      B : -0.6065937876701355 5.2570109367370605 0.2375580370426178
      C : -1.1234886646270752 0.0738643929362297 3.4047610759735107
    pbc : True True True
PeriodicSite: O (4.259, 3.66, 0.5137) [0.918, 0.5453, 0.2605]
PeriodicSite: Sb (-0.04379, 5.327, 0.699) [0.138, 0.9889, 0.1585]
PeriodicSite: Pb (1.545, 5.2, 2.931) [0.5798, 0.8837, 0.8925]
PeriodicSite: Ca (0.02707, 3.341, 0.6784) [0.1121, 0.6151, 0.1744]
PeriodicSite: O (4.063, 3.841, 1.55) [0.9491, 0.5703, 0.568]]
step: 1
CaSbPbO2
[Structure Summary
Lattice
    abc : 5.527664652056582 5.372567724143452 3.4327199287546573
 angles : 83.38058475321054 110.12202914818461 89.52856381246002
 volume : 94.95811662893377
      A : 5.442102909088135 0.747792363

 10%|█         | 5/50 [00:02<00:19,  2.28it/s]

sigma step: 5
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 5.517815372743933 5.820579151450436 3.077143065146917
 angles : 70.48580564745212 104.4554814323415 87.71243973107187
 volume : 89.37555041349005
      A : 5.4420905113220215 0.8092567324638367 -0.41837888956069946
      B : -0.5669983625411987 5.752054214477539 0.6866781115531921
      C : -0.6455400586128235 0.6251681447029114 2.943000555038452
    pbc : True True True
PeriodicSite: O (0.2622, 0.7281, 0.8069) [0.08871, 0.08508, 0.2669]
PeriodicSite: Sb (2.577, 4.089, 0.2809) [0.5423, 0.6319, 0.02511]
PeriodicSite: Pb (3.612, 0.7583, 0.06576) [0.6797, 0.02388, 0.1134]
PeriodicSite: Ca (2.226, 1.081, 1.836) [0.4948, 0.04407, 0.6838]
PeriodicSite: O (1.507, 4.736, 1.652) [0.4052, 0.7172, 0.4515]]
step: 1
CaSbPbO2
[Structure Summary
Lattice
    abc : 5.5374829283403795 5.757378936456378 2.906953262694698
 angles : 66.96495374546294 101.03146820577986 86.62313082938554
 volume : 82.78897934689287
      A : 5.4671716690063

 12%|█▏        | 6/50 [00:02<00:20,  2.14it/s]

step: 9
CaSbPbO2
[Structure Summary
Lattice
    abc : 5.147505798024779 5.806079057110276 2.777396842392402
 angles : 58.88006729360431 94.61272201562802 83.38856429974659
 volume : 69.62703103005735
      A : 5.024814605712891 1.1053863763809204 -0.16178713738918304
      B : -0.5392289161682129 5.702829837799072 0.9473742842674255
      C : -0.366374671459198 1.0007154941558838 2.5648140907287598
    pbc : True True True
PeriodicSite: O (0.2262, 6.704, 3.222) [0.2159, 0.974, 0.9099]
PeriodicSite: Sb (2.829, 3.761, 2.505) [0.6674, 0.3757, 0.8802]
PeriodicSite: Pb (3.498, 6.987, 2.558) [0.848, 0.937, 0.7049]
PeriodicSite: Ca (1.313, 6.089, 2.521) [0.4046, 0.8687, 0.6876]
PeriodicSite: O (3.047, 1.879, 0.5545) [0.6388, 0.1718, 0.193]]
sigma step: 6
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 5.161890515462372 5.777974316393921 2.6762486839107336
 angles : 57.32683266266737 94.26986846780193 86.89163718680614
 volume : 66.57775737006719
      A : 5.065850257873535 0.95761483907

 14%|█▍        | 7/50 [00:03<00:22,  1.94it/s]

step: 7
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.8865394128358846 5.496227495262026 2.814611523570103
 angles : 54.57050154144188 97.88947137852323 93.45432811057493
 volume : 60.995324155726735
      A : 4.820714473724365 0.7490313053131104 -0.27916213870048523
      B : -1.0932691097259521 5.277459144592285 1.0778238773345947
      C : -0.4127240777015686 1.0905896425247192 2.5617008209228516
    pbc : True True True
PeriodicSite: O (1.543, 6.473, 3.31) [0.6157, 0.94, 0.9638]
PeriodicSite: Sb (0.2381, 3.919, 2.626) [0.242, 0.5377, 0.8251]
PeriodicSite: Pb (-0.355, 1.493, 2.576) [0.02744, 0.0773, 0.9759]
PeriodicSite: Ca (0.8716, 2.284, 2.523) [0.3054, 0.196, 0.9358]
PeriodicSite: O (0.358, 2.021, 0.8418) [0.1641, 0.3154, 0.2138]]
step: 8
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.967624772439285 5.434107548480056 2.7642857485324703
 angles : 53.35817494990367 96.4379902926392 95.03185923339215
 volume : 59.47658447208917
      A : 4.9128217697143555 0.6905980110168457 -0.

 16%|█▌        | 8/50 [00:04<00:23,  1.75it/s]

step: 8
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.867777766481156 5.180513647863323 2.8319075920647765
 angles : 56.35325520544141 104.30730824972896 100.24001527902105
 volume : 57.532083241477764
      A : 4.819877624511719 0.39681276679039 -0.5536963939666748
      B : -1.2468513250350952 4.9641265869140625 0.8003315925598145
      C : -0.5029491782188416 1.0981919765472412 2.561389684677124
    pbc : True True True
PeriodicSite: O (-0.05482, 4.497, 2.813) [0.262, 0.6763, 0.9436]
PeriodicSite: Sb (0.84, 3.93, 1.569) [0.3942, 0.6507, 0.4944]
PeriodicSite: Pb (1.867, 0.3093, -0.1591) [0.396, 0.02735, 0.01492]
PeriodicSite: Ca (1.733, 1.785, 2.35) [0.4892, 0.1011, 0.9917]
PeriodicSite: O (1.482, 0.8481, 0.2155) [0.3503, 0.1155, 0.1238]]
step: 9
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.980457391791044 5.14600749217927 2.872304253966855
 angles : 56.03362140691195 103.49965532857675 100.15501327831531
 volume : 59.27124195202995
      A : 4.944602012634277 0.3832342028617859

 18%|█▊        | 9/50 [00:04<00:24,  1.66it/s]

step: 7
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.980679620230461 4.743579189580792 2.9342435788714463
 angles : 53.792841243460856 104.99482936359426 96.15774339852666
 volume : 53.94039698773131
      A : 4.907368183135986 0.7083038091659546 -0.47245392203330994
      B : -1.0751152038574219 4.517317295074463 0.9692859649658203
      C : -0.6743869185447693 1.0935466289520264 2.638018846511841
    pbc : True True True
PeriodicSite: O (-0.4781, 3.347, 1.825) [0.1025, 0.6068, 0.4873]
PeriodicSite: Sb (3.538, 1.382, 1.179) [0.8089, 0.03938, 0.5772]
PeriodicSite: Pb (2.687, 4.56, 1.586) [0.7804, 0.7767, 0.4556]
PeriodicSite: Ca (2.858, 1.796, 0.1803) [0.6542, 0.2746, 0.08462]
PeriodicSite: O (-0.6724, 3.631, 0.8741) [0.0419, 0.7851, 0.05038]]
step: 8
CaSbPbO2
[Structure Summary
Lattice
    abc : 5.048728416313076 4.694950842288626 2.9217647581741306
 angles : 52.989872147850996 106.98312390523131 97.19671495607616
 volume : 52.77534165728774
      A : 4.961096286773682 0.7082831263

 20%|██        | 10/50 [00:05<00:23,  1.68it/s]

step: 8
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.841553521320862 4.7015239368818085 3.0978747975943444
 angles : 43.33577669024312 99.13534432809476 101.64452632312229
 volume : 47.38965669346136
      A : 4.768810272216797 0.7446503639221191 -0.3802432417869568
      B : -1.5375458002090454 4.2819743156433105 1.1853169202804565
      C : -0.5329732298851013 1.5559076070785522 2.625246524810791
    pbc : True True True
PeriodicSite: O (1.119, 3.012, 0.974) [0.4361, 0.562, 0.1804]
PeriodicSite: Sb (1.231, 4.168, 1.305) [0.5406, 0.8018, 0.2135]
PeriodicSite: Pb (2.721, 3.889, 0.812) [0.817, 0.7305, 0.09782]
PeriodicSite: Ca (2.704, 3.389, 1.492) [0.7761, 0.4896, 0.4595]
PeriodicSite: O (-0.7226, 3.491, 2.405) [0.102, 0.5496, 0.6825]]
step: 9
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.825918461533398 4.716556354155997 3.1611874372850486
 angles : 42.55473601568659 98.89158786431696 101.89881870433368
 volume : 47.6161278507351
      A : 4.746220588684082 0.7959164977073669 -0.

 22%|██▏       | 11/50 [00:06<00:23,  1.63it/s]

sigma step: 11
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.700634481229504 4.8855168087305065 3.0692106653499813
 angles : 41.295007672874526 101.15884871804217 101.34872669555088
 volume : 45.49197799803881
      A : 4.6303534507751465 0.7973738312721252 -0.14137333631515503
      B : -1.7044025659561157 4.433066368103027 1.145080327987671
      C : -0.7999792098999023 1.5874660015106201 2.502007007598877
    pbc : True True True
PeriodicSite: O (2.034, 1.667, 0.263) [0.5421, 0.275, 0.009869]
PeriodicSite: Sb (2.332, 5.912, 2.567) [0.958, 0.9262, 0.6563]
PeriodicSite: Pb (2.061, 5.632, 3.048) [0.8911, 0.7843, 0.9098]
PeriodicSite: Ca (2.17, 3.825, 1.466) [0.7511, 0.6012, 0.3533]
PeriodicSite: O (1.154, 3.721, 2.073) [0.5474, 0.518, 0.6224]]
step: 1
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.659640478243711 4.879055840770084 2.9975036224237988
 angles : 39.84834352841646 101.08132154434871 101.72008843531904
 volume : 42.68404814362513
      A : 4.59320068359375 0.7781

 24%|██▍       | 12/50 [00:06<00:26,  1.43it/s]

step: 9
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.747148427137704 4.776675223281379 2.950121353780207
 angles : 41.39716841832848 99.51926915931222 104.12896763406108
 volume : 42.88184326438821
      A : 4.70809268951416 0.5988174080848694 -0.10343658924102783
      B : -1.7158769369125366 4.385412216186523 0.8003450632095337
      C : -0.6619309186935425 1.7328060865402222 2.2940022945404053
    pbc : True True True
PeriodicSite: O (1.572, 2.95, 1.9) [0.5491, 0.3022, 0.7476]
PeriodicSite: Sb (3.422, 2.747, 1.14) [0.9084, 0.3362, 0.4206]
PeriodicSite: Pb (-0.352, 1.757, 1.497) [0.06594, 0.1538, 0.602]
PeriodicSite: Ca (2.531, 2.715, 0.6485) [0.7265, 0.4583, 0.1556]
PeriodicSite: O (0.799, 4.27, 1.223) [0.4988, 0.7957, 0.2782]]
sigma step: 12
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.702794004909053 4.695973863933798 2.9594804553278933
 angles : 41.096578860128574 100.43656322512736 102.66702954370164
 volume : 41.90310664489985
      A : 4.651322364807129 0.6823998

 26%|██▌       | 13/50 [00:07<00:27,  1.36it/s]

step: 8
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.482489975078344 4.4238094309620335 2.890112635265228
 angles : 44.30724133414468 100.73477050557132 99.59094254519832
 volume : 39.284431138823535
      A : 4.405920028686523 0.8222100138664246 -0.06749644875526428
      B : -1.5052764415740967 4.103793621063232 0.6805223226547241
      C : -0.8023395538330078 1.5535552501678467 2.3011884689331055
    pbc : True True True
PeriodicSite: O (2.648, 2.007, 1.348) [0.7471, 0.1232, 0.5711]
PeriodicSite: Sb (3.309, 3.458, 0.7919) [0.9826, 0.5682, 0.2049]
PeriodicSite: Pb (0.1536, 2.0, 1.508) [0.2179, 0.2175, 0.5973]
PeriodicSite: Ca (1.585, 3.641, 0.9036) [0.6308, 0.6815, 0.2097]
PeriodicSite: O (1.194, 3.304, 1.335) [0.5327, 0.5324, 0.4382]]
step: 9
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.5177752270348615 4.388243485224544 2.8196785727357567
 angles : 43.35510567114253 101.28183263599931 99.7516542815038
 volume : 37.60450367708679
      A : 4.448919773101807 0.7740054130554199 

 28%|██▊       | 14/50 [00:08<00:27,  1.30it/s]

sigma step: 14
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.458794825053417 4.182502382157411 3.0542108668854175
 angles : 42.98233032274026 98.12121344917574 102.8881439720788
 volume : 37.83337720063478
      A : 4.420774936676025 0.5805635452270508 -0.023371374234557152
      B : -1.4466640949249268 3.8757972717285156 0.6153736114501953
      C : -0.6571812033653259 1.786661148071289 2.388338088989258
    pbc : True True True
PeriodicSite: O (2.895, 3.392, 1.404) [0.8964, 0.5285, 0.4606]
PeriodicSite: Sb (-0.2911, 2.78, 0.8799) [0.1605, 0.593, 0.2172]
PeriodicSite: Pb (1.863, 1.978, 1.055) [0.56, 0.25, 0.3828]
PeriodicSite: Ca (1.874, 5.277, 2.627) [0.8268, 0.8247, 0.8956]
PeriodicSite: O (0.4713, 3.186, 1.34) [0.3572, 0.5767, 0.4158]]
step: 1
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.473526444273624 4.123710808162919 3.032179082045506
 angles : 42.57633388952904 98.18546776190553 102.29406668127581
 volume : 36.96819895278793
      A : 4.431983470916748 0.605625629

 30%|███       | 15/50 [00:09<00:27,  1.26it/s]

step: 9
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.463097176692063 4.031108022774353 3.1693758043992672
 angles : 41.72048327936062 94.91641685795787 103.88168210966545
 volume : 36.45220293760024
      A : 4.417537212371826 0.6360777616500854 0.0025430377572774887
      B : -1.5069881677627563 3.6772940158843994 0.6755200028419495
      C : -0.5514991879463196 1.914419174194336 2.464911937713623
    pbc : True True True
PeriodicSite: O (2.774, 3.668, 1.891) [0.8832, 0.5201, 0.6236]
PeriodicSite: Sb (0.6819, 2.81, 0.5005) [0.3912, 0.6893, 0.01372]
PeriodicSite: Pb (1.554, 2.072, 1.406) [0.4883, 0.2125, 0.5118]
PeriodicSite: Ca (2.747, 4.733, 2.813) [0.9533, 0.6164, 0.9713]
PeriodicSite: O (1.073, 2.841, 0.8153) [0.47, 0.6056, 0.1643]]
sigma step: 15
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.421739052672562 4.0543632667588865 3.134466684642859
 angles : 41.21532797507586 94.16609392625774 102.80239637402165
 volume : 35.7155632572201
      A : 4.365859031677246 0.6993

 32%|███▏      | 16/50 [00:10<00:28,  1.20it/s]

step: 8
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.505856644219473 4.0057944895736775 3.1123565505255213
 angles : 41.74913775151765 91.6551123934107 104.68404039166624
 volume : 35.04705793607045
      A : 4.450441360473633 0.692326009273529 -0.13038593530654907
      B : -1.562204122543335 3.59173583984375 0.8398460745811462
      C : -0.31115636229515076 1.8787521123886108 2.461754560470581
    pbc : True True True
PeriodicSite: O (2.175, 3.765, 1.253) [0.771, 0.745, 0.2956]
PeriodicSite: Sb (1.586, 2.05, 2.08) [0.4305, 0.04129, 0.8536]
PeriodicSite: Pb (1.408, 2.803, 1.152) [0.5187, 0.5127, 0.3207]
PeriodicSite: Ca (2.457, 5.148, 2.749) [0.8932, 0.7941, 0.8931]
PeriodicSite: O (0.6555, 4.488, 2.669) [0.4564, 0.7081, 0.8667]]
step: 9
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.505388468808963 3.9899794460406155 3.0630446046856608
 angles : 41.10875376848332 93.29067545885192 104.16381992957696
 volume : 34.39928315822851
      A : 4.450761318206787 0.6787959933280945 -0.168

 34%|███▍      | 17/50 [00:11<00:29,  1.13it/s]

step: 9
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.335362225834419 3.8891090183344397 3.0623676913308784
 angles : 38.20291273699873 93.12847156221477 103.35356045569593
 volume : 30.370409068175448
      A : 4.302189826965332 0.527776837348938 -0.08933046460151672
      B : -1.3264747858047485 3.5687408447265625 0.7935504913330078
      C : -0.36246103048324585 1.9733442068099976 2.313575267791748
    pbc : True True True
PeriodicSite: O (2.43, 3.905, 1.081) [0.8459, 0.8549, 0.2067]
PeriodicSite: Sb (1.185, 3.467, 2.147) [0.4849, 0.4642, 0.7877]
PeriodicSite: Pb (1.816, 2.365, 0.4892) [0.5954, 0.5492, 0.04608]
PeriodicSite: Ca (-0.3069, 1.958, 1.723) [0.03661, 0.1612, 0.691]
PeriodicSite: O (0.5608, 5.166, 2.521) [0.4867, 0.9412, 0.7855]]
sigma step: 17
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.312676783218351 3.9020709361373034 3.1122306250507212
 angles : 37.755041058932306 94.44597944351943 104.02020313622909
 volume : 30.533977512404956
      A : 4.2804985046386

 36%|███▌      | 18/50 [00:12<00:29,  1.08it/s]

sigma step: 18
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.250230837159272 3.80553463235859 3.040953999282573
 angles : 36.94182090044538 95.53026279306809 103.69480430307352
 volume : 28.354921268064324
      A : 4.2186713218688965 0.47960564494132996 -0.19301003217697144
      B : -1.2705814838409424 3.502934455871582 0.7727656364440918
      C : -0.418038934469223 1.9899835586547852 2.261108160018921
    pbc : True True True
PeriodicSite: O (2.915, 3.437, 0.5646) [0.9441, 0.8244, 0.04853]
PeriodicSite: Sb (0.7691, 3.889, 1.963) [0.4492, 0.6623, 0.68]
PeriodicSite: Pb (1.574, 4.247, 2.444) [0.6446, 0.5942, 0.9327]
PeriodicSite: Ca (-0.3347, 1.704, 1.116) [0.03602, 0.2475, 0.412]
PeriodicSite: O (1.528, 1.721, 1.351) [0.4481, 0.0856, 0.6063]]
step: 1
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.2228639548124915 3.8155954960663636 3.070793879278402
 angles : 37.10283736423772 95.75344810387512 103.58511195117435
 volume : 28.69115719108773
      A : 4.191163063049316 0.4

 38%|███▊      | 19/50 [00:13<00:29,  1.04it/s]

sigma step: 19
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.031501950612496 3.8527849602380773 3.0786461807913916
 angles : 38.97588248473046 95.57590263397185 103.39783757420196
 volume : 28.989059717650996
      A : 4.013267517089844 0.37019050121307373 -0.0982385203242302
      B : -1.2094647884368896 3.584017753601074 0.7320953607559204
      C : -0.4231342375278473 1.951404333114624 2.343297004699707
    pbc : True True True
PeriodicSite: O (0.4203, 0.3675, 0.1139) [0.1297, 0.07195, 0.03155]
PeriodicSite: Sb (1.162, 4.043, 1.641) [0.5838, 0.8111, 0.4712]
PeriodicSite: Pb (1.458, 4.239, 2.502) [0.6468, 0.6263, 0.899]
PeriodicSite: Ca (-0.2806, 1.961, 1.239) [0.06725, 0.3022, 0.4372]
PeriodicSite: O (0.5895, 2.076, 1.355) [0.2831, 0.2756, 0.5042]]
step: 1
CaSbPbO2
[Structure Summary
Lattice
    abc : 4.05098403490895 3.8691233569564 3.080042073840726
 angles : 40.05665710309418 95.44025791532269 103.8002752783801
 volume : 29.87181091922858
      A : 4.031437397003174 0.3

 40%|████      | 20/50 [00:14<00:30,  1.02s/it]

sigma step: 20
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 3.994001632135924 3.728783638458182 3.0489394580227156
 angles : 38.68458167003442 98.56718954614024 105.96321401961805
 volume : 27.122909245019752
      A : 3.9829039573669434 0.2661362290382385 -0.13302861154079437
      B : -1.235304355621338 3.447662115097046 0.7010538578033447
      C : -0.5067151784896851 1.9224644899368286 2.311579942703247
    pbc : True True True
PeriodicSite: O (-0.5048, 2.917, 2.447) [0.08906, 0.2964, 0.9737]
PeriodicSite: Sb (2.414, 1.122, 0.8988) [0.672, 0.04219, 0.4147]
PeriodicSite: Pb (0.9205, 4.713, 2.621) [0.5985, 0.8055, 0.9239]
PeriodicSite: Ca (-0.3147, 2.135, 1.189) [0.09245, 0.3879, 0.402]
PeriodicSite: O (0.2614, 2.194, 1.242) [0.2373, 0.3741, 0.4374]]
step: 1
CaSbPbO2
[Structure Summary
Lattice
    abc : 3.9433970645003362 3.7159903278417747 3.0743342558159403
 angles : 38.91673988303032 98.21672535818455 105.29647831739177
 volume : 27.152622749964117
      A : 3.93258547782

 42%|████▏     | 21/50 [00:15<00:31,  1.07s/it]

sigma step: 21
step: 0
CaSbPbO2
[Structure Summary
Lattice
    abc : 3.864435927875969 3.711665246600488 3.016618531856149
 angles : 39.45370952385845 97.90755508405154 104.53049186840822
 volume : 26.50480555388146
      A : 3.854923963546753 0.2709718942642212 0.000713057117536664
      B : -1.1759871244430542 3.447288990020752 0.7139410376548767
      C : -0.5457789897918701 1.8396388292312622 2.3276257514953613
    pbc : True True True
PeriodicSite: O (-0.4318, 3.3, 2.566) [0.1557, 0.4267, 0.9714]
PeriodicSite: Sb (2.25, 1.396, 1.181) [0.6807, 0.09652, 0.4775]
PeriodicSite: Pb (1.097, 5.347, 2.89) [0.7205, 0.9948, 0.9365]
PeriodicSite: Ca (-0.003072, 2.441, 1.361) [0.2009, 0.4546, 0.4453]
PeriodicSite: O (-0.005176, 2.58, 1.529) [0.2109, 0.4558, 0.5171]]
step: 1
CaSbPbO2
[Structure Summary
Lattice
    abc : 3.8587645290180266 3.734476626344106 2.987372164584617
 angles : 39.05155750234215 97.58117111437855 104.79457012460375
 volume : 26.066684372035205
      A : 3.84932279586792 0

 44%|████▍     | 22/50 [00:17<00:31,  1.13s/it]

In [25]:
lattices = results['lattices']
num_atoms = results['num_atoms']
frac_coords = results['frac_coords']
atom_types = results['atom_types']

print(lattices.shape)
print(num_atoms)
print(frac_coords.shape)
print(atom_types.shape)

torch.Size([1, 3, 3])
tensor([5])
torch.Size([5, 3])
torch.Size([5])


In [28]:
from pymatgen.core import Structure, Lattice, Element

In [35]:
s = Structure(
    lattice = lattices[0].detach().numpy(), 
    species = atom_types.detach().numpy(), 
    coords = frac_coords.detach().numpy(),
    to_unit_cell = False,
    coords_are_cartesian = False,
)

In [38]:
s.to(filename = 'test.cif')

"# generated using pymatgen\ndata_BaPbO2F\n_symmetry_space_group_name_H-M   'P 1'\n_cell_length_a   3.53783707\n_cell_length_b   3.42190810\n_cell_length_c   3.94141020\n_cell_angle_alpha   89.86521189\n_cell_angle_beta   98.67320852\n_cell_angle_gamma   87.74474157\n_symmetry_Int_Tables_number   1\n_chemical_formula_structural   BaPbO2F\n_chemical_formula_sum   'Ba1 Pb1 O2 F1'\n_cell_volume   47.13147335\n_cell_formula_units_Z   1\nloop_\n _symmetry_equiv_pos_site_id\n _symmetry_equiv_pos_as_xyz\n  1  'x, y, z'\nloop_\n _atom_site_type_symbol\n _atom_site_label\n _atom_site_symmetry_multiplicity\n _atom_site_fract_x\n _atom_site_fract_y\n _atom_site_fract_z\n _atom_site_occupancy\n  O  O0  1  0.47707206  0.26089239  0.72417396  1\n  F  F1  1  0.24421930  0.76086646  0.22002952  1\n  O  O2  1  0.78258717  0.25923207  0.22578231  1\n  Ba  Ba3  1  0.10901868  0.77228439  0.21699725  1\n  Pb  Pb4  1  0.28334343  0.75352079  0.73077738  1\n"